### ISSUE TITLE
A question about motifs.

### ISSUE THREAD

**Issue by gyy8426** [rowanz/neural-motifs#10]
Thanks for sharing code. But my concept of motifs is not very clear. Do you mind telling me which code or pseudocode is generating motifs ?

**Comment by rowanz** [comment]
this code doesn't 'generate' motifs, rather, the point is that our model is global over the entire set of object proposals, which allows it to capture higher order priors (motifs) during scene graph generation. I highly recommend you check out the paper [here for more info](https://arxiv.org/abs/1711.06640) 😃

**Comment by gyy8426** [comment]
I have read this paper. I mean, in the section _Larger Motifs_, there are some example motifs in the dataset, _can_ you share the code for this experiment in _Larger Motifs_?

**Comment by rowanz** [comment]
oh, good question. Should be fixed by commit 252274f474444d57578c9e3afd3c661a088f275d

**Comment by gyy8426** [comment]
Thanks a lot!!!
