### ISSUE TITLE
After changing pytorch 0.4.0 to 0.3.0 glove file should be re-downloaded(solved)

### ISSUE THREAD

**Issue by LinXin2018** [rowanz/neural-motifs#11]
Hi, Roman：
I have change pytorch 0.4.0 to 0.3.0; Under 0.4.0, the code can run the baseline model (./scripts/train_models_sgcls.sh 0); it downloads the glove file for the first time and process it. 
However, after changing the pytorch version, the processed files are not compatible with 0.3.0 and the code does not judge it and report errors. 
So, the processed files should be removed or remove all the glove file and let the code download and process it under the current pytorch version.

**Comment by bamos** [comment]
This is a confusing issue that I hit too that has an easy fix. I've added a check to the code in #17 to make this clearer.

**Comment by rowanz** [comment]
thanks for the PR warning for this @bamos!! I'll close this issue for now :)
