### ISSUE TITLE
How to visualize the results?

### ISSUE THREAD

**Issue by YiwuZhong** [rowanz/neural-motifs#12]
After training and evaluation, how can I visualize the image with boxes and corresponding scene graph?
Also, in the row 320 of lib/object_detector.py, does it mean we need to modify the code if we train models like sgdet? Because when the mode is sgdet, the statement of "if" branch will never run.

Thanks!

**Comment by rowanz** [comment]
Hi Yiwu, see /models/_visualize.py 

also thanks for spotting that, there was a bug with 39b5cdb that I just fixed now. should work now 😄
