### ISSUE TITLE
The checkpoint file is damaged?

### ISSUE THREAD

**Issue by zhangshuai1207** [rowanz/neural-motifs#13]
Hello, I have downloaded the chechpoint file "vgrel-motifnet-sgdet.tar",but i can't uncompress it. Maybe it is damaged? Can you reupload it again?

**Comment by rowanz** [comment]
sorry for the confusion, it's not actually a tar file, it's the pickle format or w/e pytorch uses to save stuff. so it should be okay after all 😄
