### ISSUE TITLE
About the usage of flags

### ISSUE THREAD

**Issue by hellochick** [rowanz/neural-motifs#15]
Hey! Really appreciate this amazing work.
I have a little question about these four flags: `-gt_box`, `-old_feat`,  `-pass_in_obj_feats_to_decoder`, `-pass_in_obj_feats_to_edge`.
Could you please explain these flags? Thank you a lot.

Btw, I am trying to use MaskRCNN to extract features and predict the relations between instances. Is there any suggestions? Hope to hear from you soon! 

Best wishes,
HsuanKung

**Comment by rowanz** [comment]
Sure! the only one that really matters is `-gt_box` as that controls whether we train/eval on ground truth boxes or on predicted boxes. `-old_feats` doesn't do anything right now. `-pass_in_obj_feats_to_decoder/edge` controls whether we want to duplicate the object features (from Faster RCNN) for object/edge classifications. Anyways, you might want to look at the scripts directory, which has the flags I used.

MaskRCNN is built on top of Faster RCNN, but it doesn't make sense to train it on this dataset as Visual Genome doesn't have segmentations. It also just does object detection/segmentation, so not relations. You'll need another model on top of the detector for that (like MotifNet or one of the baselines). hope that helps!
