### ISSUE TITLE
how to re-implement the result in no graph constraints ???

### ISSUE THREAD

**Issue by akira-l** [rowanz/neural-motifs#19]
I got the result in graph constraints with given code and parameters, but where is the no constraints part?
How to implement no graph constraints ? 

Check relation index (rel_inds in rel_model.py) and make sure every proposal only have one relation to another proposal area ?

**Comment by rowanz** [comment]
Use the -multipred option - let me know if that doesn’t work :)

**Comment by akira-l** [comment]
OK THANKS!

**Comment by akira-l** [comment]
oh, by the way, those checkpoints given in your google drives were trained in graph constraints ? Should I train again with no graph constraints ?

**Comment by akira-l** [comment]
oh, my mistake, may be the with/without graph constraints just like reranking in retrieval. The constraints are not relevent to the network model training, right?
