### ISSUE TITLE
import issues

### ISSUE THREAD

**Issue by galsk87** [rowanz/neural-motifs#21]
while trying to train i'm getting the next error

n.anchor_targets import anchor_target_layer
  File "/home/sgalk87/neural-motifs/lib/fpn/anchor_targets.py", line 12, in <module>
    from lib.fpn.box_intersections_cpu.bbox import bbox_overlaps
ImportError: No module named 'lib.fpn.box_intersections_cpu.bbox'
 seems like a problem with the relative imports, did you solve it?

**Comment by rowanz** [comment]
what's your PYTHONPATH variable?

**Comment by galsk87** [comment]
Close.
