### ISSUE TITLE
Adaption to small image.

### ISSUE THREAD

**Issue by zhiyong1997** [rowanz/neural-motifs#24]
Hi, Rowan,
I'd like to resize the image to 224 × 224 instead of 592 × 592. I think I should change IM_SCALE and ANCHOR_SIZE. Are those all I have to change?

Thanks!

**Comment by zhiyong1997** [comment]
BTW, do you think the performance will drop or increase if I do so?

Thanks

**Comment by rowanz** [comment]
I think so but am not sure. In any case, I’m pretty sure performance would
go down as it’ll be hard to detect objects in such a small image.
