### ISSUE TITLE
Why feeding roi feature to vgg again?

### ISSUE THREAD

**Issue by zhydong** [rowanz/neural-motifs#29]
In `rel_model.py`, `obj_feature_map()`, you feed the pooled features(`feature_pool`) from RoIAlign layer to vgg Net again to generate roi features. Why not returning `feature_pool` directly?

related codes :
```
self.roi_fmap_obj = load_vgg(pretrained=False).classifier
```
```
def obj_feature_map(self, features, rois):
    """
    Gets the ROI features
    :param features: [batch_size, dim, IM_SIZE/4, IM_SIZE/4] (features at level p2)
    :param rois: [num_rois, 5] array of [img_num, x0, y0, x1, y1].
    :return: [num_rois, #dim] array
    """
    feature_pool = \
RoIAlignFunction(self.pooling_size, self.pooling_size, spatial_scale=1 / 16)(features, rois)
    return self.roi_fmap_obj(feature_pool.view(rois.size(0), -1))
```

**Comment by rowanz** [comment]
You could do that if you wanted to, however the standard VGG implementation
when used in object detection uses two FC layers after the last convolution
(or in this case, after the RoIPool). so that's where self.roi_fmap_obj is
coming from :)
