### ISSUE TITLE
How to implement the "NO SCENE GRAPH CONSTRAINT” on associate embedding?

### ISSUE THREAD

**Issue by sim-l3** [rowanz/neural-motifs#30]
To my best knowledge, the experiment results in associate embedding (9.7, 11.3..... ) should be under the constraint of the scene graph. However, you have cited the result of associate embedding in the column of non-scene graph constraint. Could you help me to figure it out? Thanks

**Comment by rowanz** [comment]
Nope, we checked with the authors and they don’t use the scene graph
constraints of Xu et al. To get their fixed numbers, I used a script to
process the outputs that the authors shared with me :)

**Comment by sim-l3** [comment]
Thanks for your reply. Now, The paper is much more clear to me.

**Comment by sim-l3** [comment]
Thanks for your reply. Now, The paper is much more clear to me.
