### ISSUE TITLE
how to run the code

### ISSUE THREAD

**Issue by wtliao** [rowanz/neural-motifs#32]
Hi, thanks for sharing your impressive work and code. When I try to run the code, I have enountered some problems.

1. when I ran ./scripts/pretrain_detector.sh, the error is
Traceback (most recent call last):
  File "models/train_detector.py", line 7, in <module>
    from dataloaders.mscoco import CocoDetection, CocoDataLoader
ModuleNotFoundError: No module named 'dataloaders'

I try to comment the import module, and then the error arises for importing other modules. I try to directly import any of the given module in python. It works. It seems that it can't recognized the module when I try to run the .sh. This error also presents when I run other .sh file. Could you give me a solution that I don't  need to run any of them in .sh. Thanks a lot

**Comment by sim-l3** [comment]
You should change the PYTHONPATH.

**Comment by wtliao** [comment]
@sim-l3 do you mean to execute 
export PYTHONPATH=/home/rowan/code/scene-graph 
in terminal? I tried to do it as: 
export PYTHONPATH=/home/wtliao/code/neural-motifs-master
export PYTHONPATH=/home/wtliao/code/scene-graph
export PYTHONPATH=/home/rowan/code/scene-graph

but none of them works. Could help me? I'm not familiar with enviroment setting. Thanks

**Comment by wtliao** [comment]
I solved it by
export PYTHONPATH=~/code/neural-motifs-master

thanks

**Comment by rowanz** [comment]
awesome!
