### ISSUE TITLE
Training sgcls with ResNet ?

### ISSUE THREAD

**Issue by FrancoisPl** [rowanz/neural-motifs#36]
Hi!
I have successfully pretrained an object detector with ResNet but I've been unable to to train the rel detection model. I think there is something I do not understand (namely the differences between and use cases of detector.roi_fmap and rel_model.roi_fmap).
I guess the ResNet part of the code is depecrated now, do you have an updated version?
Or some ideas about how to update it?
I would be very grateful :-)

**Comment by FrancoisPl** [comment]
Hi Rowan!

Thank you for your answer! 
I've made a few changes to the code to use resnet 34 (I had memory issues with resnet 101) and made a Pull request with the changed code, if you're interested or want to give me some feedback?

Furthermore, on my end, the training takes a long time before it starts. Do you know why and did you simply use a smaller dataset when iterating on the code?

Thanks again!!

**Comment by rowanz** [comment]
thanks again for the PR! My guess as for why it takes a while before training begins is that you have to initialize Resnet (or whatever CNN you're using), but I'm not sure.

**Comment by jiayanyang97** [comment]
Hi Francois!

I have successfully pretrained VG detection with ResNet 34 using your changed code.
But I have the following issue when training VG scene graph classification:

`Traceback (most recent call last):
  File "models/traln_rels.py", line 206, in <module> 
      rez = train_epoch(epoch)
  File "models/train_rels.py", line 117, in train_epoch
      tr.append(train_batch(batch, verbose=b % (conf.print_lnterval*10) == 0)) #b == 0))
  File "models/train_rels.py", line 149, in tratn_batch 
      result = detector[b]
  File "/datal/yjy/Documents/Neural-Motlfs/lib/rel_model.py", line 568, in _getitem_
      return self(*batch[0])
  File "/data1/yjy/.conda/envs/python3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
      result = self.forward(*input, **kwargs)
  File "/data1/yjy/Documents/Neural-Motlfs/lib/rel_model.py", line 534, in forward
      prod_rep = prod_rep * vr
RuntimeError: The size of tensor a (4096) must match the size of tensor b (2048) at non-singleton dimension 1`

Do you have any idea about that? Thanks!

**Comment by galsk87** [comment]
@FrancoisPl can you share your code?
