### ISSUE TITLE
miss file "lib/rel_model_baseline.py"

### ISSUE THREAD

**Issue by yuweihao** [rowanz/neural-motifs#4]
Thanks for your nice code. The file "lib/rel_model_baseline.py" is missing, could you please upload it and its checkpoints, thank you!

**Comment by rowanz** [comment]
hi! So I think there's some confusion (just committed a change to hopefully help alleviate it in the future):

If you'd like the Motifnet-NoContext baseline, then you'll need to pass "motifnet" for the model, and set the number of object and edge layers to 0 - see [https://github.com/rowanz/neural-motifs/blob/15c875456510a5fdc3454fb73a4b1d0bffec165a/scripts/train_models_sgcls.sh#L7](https://github.com/rowanz/neural-motifs/blob/15c875456510a5fdc3454fb73a4b1d0bffec165a/scripts/train_models_sgcls.sh#L7) for more info. If what you wanted was the frequency baselines, then you'll need to look into [models/eval_rel_count.py](https://github.com/rowanz/neural-motifs/blob/15c875456510a5fdc3454fb73a4b1d0bffec165a/models/eval_rel_count.py#L1). hope that helps!
