### ISSUE TITLE
cudaCheckError() failed : invalid device function

### ISSUE THREAD

**Issue by ZHUXUHAN** [rowanz/neural-motifs#40]
I use the cuda8.0 pytroch0.4 and python3.6
how can I do to solve the problem?

**Comment by ZHUXUHAN** [comment]
I solved this problem by delete the  fpn/nms directory, and change the row-align to the roi-align in https://github.com/jwyang/faster-rcnn.pytorch/tree/master/lib/model/roi_align

I use the cuda8.0 pytroch0.4 and python3.6

**Comment by rowanz** [comment]
awesome! apologies, I don't support pytorch 0.4 in this project, so it's possible that's what's causing the error.

**Comment by waallf** [comment]
> I solved this problem by deleting the fpn/nms directory, and reload the nms directory,then change the roi-align to the roi-align in https://github.com/jwyag/faster-rcnn.pytorch/tree/master/lib/model/roi_align,then you can make it again.
> 
> I use the cuda8.0 pytroch0.4 and python3.6

你好，我遇到了同样的问题，我的pytorch版本是0.3.1，您能不能详细的说一下怎么解决这个问题的，谢谢
