### ISSUE TITLE
problems with preforming eval

### ISSUE THREAD

**Issue by galsk87** [rowanz/neural-motifs#41]
im running the next command 
python3 models/eval_rels.py -m sgcls  -model motifnet -order leftright -nl_obj 2 -nl_edge 4 -b 6 -clip 5 \
        -p 100 -hidden_dim 512 -pooling_dim 4096 -lr 1e-3 -ngpu 1 -test -ckpt checkpoints/motifnet2/vgrel-10.tar -nepoch 50 -cache motifnet_sgcls -use_bias

  0%|          | 0/26446 [00:00<?, ?it/s]~~~~~~~~ Hyperparameters used: ~~~~~~~
old_feats : False
pass_in_obj_feats_to_decoder : False
coco : False
rec_dropout : 0.1
batch_size : 6
nl_edge : 4
print_interval : 100
order : leftright
cache : motifnet_sgcls
model : motifnet
val_size : 5000
l2 : 0.0001
mode : sgdet
use_resnet : False
hidden_dim : 512
clip : 5.0
adam : False
use_tanh : False
lr : 0.001
multi_pred : True
use_proposals : False
num_workers : 1
num_gpus : 1
nl_obj : 2
pooling_dim : 4096
num_epochs : 50
pass_in_obj_feats_to_edge : False
test : True
limit_vision : False
det_ckpt :
gt_box : False
ckpt : checkpoints/motifnet2/vgrel-5.tar
save_dir :
use_bias : True
loading word vectors from /home/sgalk87/neural-motifs/data/glove.6B.200d.pt
__background__ -> __background__
fail on __background__
loading word vectors from /home/sgalk87/neural-motifs/data/glove.6B.100d.pt
__background__ -> __background__
fail on __background__
Unexpected key module.detector.features.0.weight in state_dict with size torch.Size([64, 3, 3, 3])
Unexpected key module.detector.features.0.bias in state_dict with size torch.Size([64])
Unexpected key module.detector.features.2.weight in state_dict with size torch.Size([64, 64, 3, 3])
Unexpected key module.detector.features.2.bias in state_dict with size torch.Size([64])
Unexpected key module.detector.features.5.weight in state_dict with size torch.Size([128, 64, 3, 3])
Unexpected key module.detector.features.5.bias in state_dict with size torch.Size([128])
Unexpected key module.detector.features.7.weight in state_dict with size torch.Size([128, 128, 3, 3])
Unexpected key module.detector.features.7.bias in state_dict with size torch.Size([128])
Unexpected key module.detector.features.10.weight in state_dict with size torch.Size([256, 128, 3, 3])
Unexpected key module.detector.features.10.bias in state_dict with size torch.Size([256])
Unexpected key module.detector.features.12.weight in state_dict with size torch.Size([256, 256, 3, 3])
Unexpected key module.detector.features.12.bias in state_dict with size torch.Size([256])
Unexpected key module.detector.features.14.weight in state_dict with size torch.Size([256, 256, 3, 3])
Unexpected key module.detector.features.14.bias in state_dict with size torch.Size([256])
Unexpected key module.detector.features.17.weight in state_dict with size torch.Size([512, 256, 3, 3])
Unexpected key module.detector.features.17.bias in state_dict with size torch.Size([512])
Unexpected key module.detector.features.19.weight in state_dict with size torch.Size([512, 512, 3, 3])
Unexpected key module.detector.features.19.bias in state_dict with size torch.Size([512])
Unexpected key module.detector.features.21.weight in state_dict with size torch.Size([512, 512, 3, 3])
Unexpected key module.detector.features.21.bias in state_dict with size torch.Size([512])
Unexpected key module.detector.features.24.weight in state_dict with size torch.Size([512, 512, 3, 3])
Unexpected key module.detector.features.24.bias in state_dict with size torch.Size([512])
Unexpected key module.detector.features.26.weight in state_dict with size torch.Size([512, 512, 3, 3])
Unexpected key module.detector.features.26.bias in state_dict with size torch.Size([512])
Unexpected key module.detector.features.28.weight in state_dict with size torch.Size([512, 512, 3, 3])
Unexpected key module.detector.features.28.bias in state_dict with size torch.Size([512])
Unexpected key module.detector.roi_fmap.0.weight in state_dict with size torch.Size([4096, 25088])
Unexpected key module.detector.roi_fmap.0.bias in state_dict with size torch.Size([4096])
Unexpected key module.detector.roi_fmap.3.weight in state_dict with size torch.Size([4096, 4096])
Unexpected key module.detector.roi_fmap.3.bias in state_dict with size torch.Size([4096])
Unexpected key module.detector.score_fc.weight in state_dict with size torch.Size([151, 4096])
Unexpected key module.detector.score_fc.bias in state_dict with size torch.Size([151])
Unexpected key module.detector.bbox_fc.weight in state_dict with size torch.Size([604, 4096])
Unexpected key module.detector.bbox_fc.bias in state_dict with size torch.Size([604])
Unexpected key module.detector.rpn_head.anchors in state_dict with size torch.Size([37, 37, 20, 4])
Unexpected key module.detector.rpn_head.conv.0.weight in state_dict with size torch.Size([512, 512, 3, 3])
Unexpected key module.detector.rpn_head.conv.0.bias in state_dict with size torch.Size([512])
Unexpected key module.detector.rpn_head.conv.2.weight in state_dict with size torch.Size([120, 512, 1, 1])
Unexpected key module.detector.rpn_head.conv.2.bias in state_dict with size torch.Size([120])
Unexpected key module.context.obj_embed.weight in state_dict with size torch.Size([151, 200])
Unexpected key module.context.obj_embed2.weight in state_dict with size torch.Size([151, 200])
Unexpected key module.context.rel_embed.weight in state_dict with size torch.Size([35390, 200])
Unexpected key module.context.pos_embed.0.weight in state_dict with size torch.Size([4])
Unexpected key module.context.pos_embed.0.bias in state_dict with size torch.Size([4])
Unexpected key module.context.pos_embed.0.running_mean in state_dict with size torch.Size([4])
Unexpected key module.context.pos_embed.0.running_var in state_dict with size torch.Size([4])
Unexpected key module.context.pos_embed.1.weight in state_dict with size torch.Size([128, 4])
Unexpected key module.context.pos_embed.1.bias in state_dict with size torch.Size([128])
Unexpected key module.context.obj_ctx_rnn.weight in state_dict with size torch.Size([17784832])
Unexpected key module.context.obj_ctx_rnn.bias in state_dict with size torch.Size([5120])
Unexpected key module.context.decoder_rnn.obj_embed.weight in state_dict with size torch.Size([152, 100])
Unexpected key module.context.decoder_rnn.input_linearity.weight in state_dict with size torch.Size([3072, 612])
Unexpected key module.context.decoder_rnn.input_linearity.bias in state_dict with size torch.Size([3072])
Unexpected key module.context.decoder_rnn.state_linearity.weight in state_dict with size torch.Size([2560, 512])
Unexpected key module.context.decoder_rnn.state_linearity.bias in state_dict with size torch.Size([2560])
Unexpected key module.context.decoder_rnn.out.weight in state_dict with size torch.Size([151, 512])
Unexpected key module.context.decoder_rnn.out.bias in state_dict with size torch.Size([151])
Unexpected key module.context.edge_ctx_rnn.weight in state_dict with size torch.Size([12148736])
Unexpected key module.context.edge_ctx_rnn.bias in state_dict with size torch.Size([10240])
Unexpected key module.union_boxes.conv.0.weight in state_dict with size torch.Size([256, 2, 7, 7])
Unexpected key module.union_boxes.conv.0.bias in state_dict with size torch.Size([256])
Unexpected key module.union_boxes.conv.2.weight in state_dict with size torch.Size([256])
Unexpected key module.union_boxes.conv.2.bias in state_dict with size torch.Size([256])
Unexpected key module.union_boxes.conv.2.running_mean in state_dict with size torch.Size([256])
Unexpected key module.union_boxes.conv.2.running_var in state_dict with size torch.Size([256])
Unexpected key module.union_boxes.conv.4.weight in state_dict with size torch.Size([512, 256, 3, 3])
Unexpected key module.union_boxes.conv.4.bias in state_dict with size torch.Size([512])
Unexpected key module.union_boxes.conv.6.weight in state_dict with size torch.Size([512])
Unexpected key module.union_boxes.conv.6.bias in state_dict with size torch.Size([512])
Unexpected key module.union_boxes.conv.6.running_mean in state_dict with size torch.Size([512])
Unexpected key module.union_boxes.conv.6.running_var in state_dict with size torch.Size([512])
Unexpected key module.roi_fmap.1.0.weight in state_dict with size torch.Size([4096, 25088])
Unexpected key module.roi_fmap.1.0.bias in state_dict with size torch.Size([4096])
Unexpected key module.roi_fmap.1.3.weight in state_dict with size torch.Size([4096, 4096])
Unexpected key module.roi_fmap.1.3.bias in state_dict with size torch.Size([4096])
Unexpected key module.roi_fmap_obj.0.weight in state_dict with size torch.Size([4096, 25088])
Unexpected key module.roi_fmap_obj.0.bias in state_dict with size torch.Size([4096])
Unexpected key module.roi_fmap_obj.3.weight in state_dict with size torch.Size([4096, 4096])
Unexpected key module.roi_fmap_obj.3.bias in state_dict with size torch.Size([4096])
Unexpected key module.post_lstm.weight in state_dict with size torch.Size([8192, 512])
Unexpected key module.post_lstm.bias in state_dict with size torch.Size([8192])
Unexpected key module.rel_compress.weight in state_dict with size torch.Size([51, 4096])
Unexpected key module.rel_compress.bias in state_dict with size torch.Size([51])
Unexpected key module.freq_bias.obj_baseline.weight in state_dict with size torch.Size([22801, 51])
We couldn't find detector.features.10.bias,context.pos_embed.0.weight,detector.features.19.bias,context.decoder_rnn.out.ight,detector.score_fc.bias,detector.rpn_head.conv.2.weight,context.obj_embed2.weight,context.decoder_rnn.state_linearitweight,detector.features.10.weight,detector.features.24.weight,detector.features.26.bias,roi_fmap.1.0.weight,detector.rphead.conv.2.bias,detector.features.14.bias,rel_compress.weight,union_boxes.conv.0.weight,roi_fmap_obj.0.weight,context.doder_rnn.state_linearity.bias,freq_bias.obj_baseline.weight,post_lstm.weight,union_boxes.conv.4.bias,detector.bbox_fc.weht,detector.features.21.bias,detector.features.17.weight,detector.features.26.weight,context.decoder_rnn.input_linearityias,roi_fmap_obj.3.bias,detector.score_fc.weight,detector.features.0.bias,context.pos_embed.0.bias,union_boxes.conv.6.ruing_mean,context.decoder_rnn.obj_embed.weight,detector.features.12.bias,context.obj_embed.weight,roi_fmap.1.3.weight,roimap_obj.0.bias,context.pos_embed.1.bias,detector.features.17.bias,union_boxes.conv.6.running_var,union_boxes.conv.6.biasontext.pos_embed.0.running_mean,detector.features.19.weight,detector.rpn_head.anchors,detector.features.21.weight,union_xes.conv.6.weight,detector.features.7.bias,detector.features.14.weight,roi_fmap.1.0.bias,roi_fmap_obj.3.weight,detector.atures.24.bias,detector.features.28.weight,context.decoder_rnn.input_linearity.weight,context.edge_ctx_rnn.weight,detect.features.7.weight,detector.roi_fmap.0.weight,detector.features.2.weight,detector.roi_fmap.3.bias,union_boxes.conv.2.runng_mean,context.decoder_rnn.out.bias,detector.features.2.bias,detector.roi_fmap.3.weight,union_boxes.conv.2.running_var,i_fmap.1.3.bias,detector.features.28.bias,context.obj_ctx_rnn.weight,detector.roi_fmap.0.bias,context.pos_embed.0.runninvar,detector.features.12.weight,union_boxes.conv.4.weight,post_lstm.bias,detector.rpn_head.conv.0.weight,detector.rpn_he.conv.0.bias,detector.features.5.bias,context.pos_embed.1.weight,context.edge_ctx_rnn.bias,union_boxes.conv.0.bias,detecr.features.5.weight,union_boxes.conv.2.weight,rel_compress.bias,union_boxes.conv.2.bias,detector.bbox_fc.bias,detector.ftures.0.weight,context.obj_ctx_rnn.bias
100%|██████████| 26446/26446 [2:29:23<00:00,  2.95it/s]
======================sgdet============================
R@100: 0.000000
R@50: 0.000000
R@20: 0.000000

**Comment by rowanz** [comment]
It looks like you trained your own checkpoint with DataParallel turned on,
which appends ‘module’ to all your parameter names. You should be able to
get it to work by modifying your checkpoint to strip the leading ‘module’
prefixes :)
