### ISSUE TITLE
Not sure RelModel is learning

### ISSUE THREAD

**Issue by galsk87** [rowanz/neural-motifs#43]
while running train_rels.py -m sgcls -model motifnet -order leftright -nl_obj 2 -nl_edge 4 -b 6 -clip 5 \
        -p 100 -hidden_dim 512 -pooling_dim 4096 -lr 1e-3 -ngpu 1 -ckpt checkpoints/vgdet/vg-24.tar \
        -save_dir checkpoints/motifnet2 -nepoch 50 -use_bias

my rel loss is constantly around 0.15-0.12 is this the loss you got while training , did you see any improvements, do you think the model might not learn like expected?

i'm getting similar results to what you published.

**Comment by rowanz** [comment]
if you're getting good results, then the model is learning, right? One thing to note is that there often isn't much to learn on top of the frequency baseline 😄

**Comment by galsk87** [comment]
You are not inputting it into the motifnet model though right?
