### ISSUE TITLE
Question about the code of rel_stanford 

### ISSUE THREAD

**Issue by lileilai** [rowanz/neural-motifs#48]
Hi~

my problem is about the stanford model of your code. the scripts of train_stanford.sh includes the item of "-ckpt checkpoints/vgdet/vg-24.tar" , but i don't find some explaining or download links about "vgdet/vg-24.tar" .
So, can you tell me the details of this file and how to get it, and more implementation details about standord model [like ..epochs ? ]

I hope you can answer my questions.  thanks~~

**Comment by rowanz** [comment]
Hi there,

that's the pretrained detector checkpoint, which you can download from the google drive link that's in the readme 😄
