### ISSUE TITLE
faster_rcnn_500k.h5 what is this network?

### ISSUE THREAD

**Issue by fate3439** [rowanz/neural-motifs#49]
Hi Rowan,

Many thanks for releasing your work! As I am trying to pretrain the detector, I found the training need to restore a checkpoint called faster_rcnn_500k.h5. If I understand it correctly, this net is a VGG network but weights are trained on some other dataset? 

Could you let me know on what dataset is this network trained, for how many epochs/hours and what is its performance on that dataset? 

Many thanks!
Chu.

**Comment by rowanz** [comment]
sorry for the confusion, I think this should be dead code. I started pretraining the detector from the pytorch provided imagenet checkpoint :)
