### ISSUE TITLE
How to generate the scene graph of a single image?

### ISSUE THREAD

**Issue by ruizewang** [rowanz/neural-motifs#52]
Hello,
How to generate the scene graph of a single image, instead of run the evaluation on the whole dataset?
Can you tell me more about that?
Thanks.

**Comment by rowanz** [comment]
I'm not sure what you mean by this - if you want a demo, the status of that is in https://github.com/rowanz/neural-motifs/issues/42, essentially, I don't have that at the moment but PRs are welcome 😄. If your goal is just to run the model in sgdet mode, then https://github.com/rowanz/neural-motifs/blob/0898c99aa3a2e57e1a94de46fa7cedf2a9c5e83a/models/eval_rels.py#L59 should do that.

**Comment by ruizewang** [comment]
Hello,
I mean, for example, there is an image called party.jpg, then the only thing I want to do is generating the scene graph of this image.
What should I do?
Thanks.

**Comment by ttxxr** [comment]
> Hello,
> I mean, for example, there is an image called party.jpg, then the only thing I want to do is generating the scene graph of this image.
> What should I do?
> Thanks.

Hello. Have you generated the scene graph on your own image successfully？ Recently,i am trying to generate my own scene graph , too . Could you please help me ?

**Comment by JingJLiu** [comment]
> > Hello,
> > I mean, for example, there is an image called party.jpg, then the only thing I want to do is generating the scene graph of this image.
> > What should I do?
> > Thanks.
> 
> Hello. Have you generated the scene graph on your own image successfully？ Recently,i am trying to generate my own scene graph , too . Could you please help me ?

Hi, I also want to test my images,did you solve the problem?

**Comment by forbiddenname** [comment]
> Hello,
> I mean, for example, there is an image called party.jpg, then the only thing I want to do is generating the scene graph of this image.
> What should I do?
> Thanks.

Hi Have you solved the problem？ tks

**Comment by JingJLiu** [comment]
Hi ,sorry,I haven't solved this problem either.


------------------&nbsp;Original&nbsp;------------------
