### ISSUE TITLE
Training Object Detector and Motifnet jointly

### ISSUE THREAD

**Issue by galsk87** [rowanz/neural-motifs#54]
Hi did you experiment unfreezing the detector's weights while training morifnet?

**Comment by rowanz** [comment]
I did originally, but ended up rerunning the experiments to freeze everything (to ensure a fair comparison with prior work). at the end of the day, if you've pretrained the detector on visual genome, that's probably enough...

**Comment by galsk87** [comment]
Also is there a version that supports a reanset backbone?

בתאריך שבת, 16 בפבר׳ 2019, 22:47, מאת Rowan Zellers <
notifications@github.com>:
