### ISSUE TITLE
Question about Checkpoints of pretrained models

### ISSUE THREAD

**Issue by tjuwyh** [rowanz/neural-motifs#57]
hi
I got some trouble when I tried to download the checkpoint of pre-trained models.
Files which I downloaded from google drive links cannot be uncompressed or viewed correctly. The error is "tar: This does not look like a tar archive"
I'm wondering did I do it in a wrong way and Is there another download link?
It troubles me a lot, could you please offer some advice. 
Thanks!

**Comment by ShiYaya** [comment]
i also meet this problem, did you solve it ?

**Comment by Lazy-poe** [comment]
I meet the same issue, how do you solve it ?
