### ISSUE TITLE
32492 Segmentation fault 

### ISSUE THREAD

**Issue by jungjun9150** [rowanz/neural-motifs#69]
Hello. 
Thank you for opening code for motifnet
in the training for train_rels.py, i got the this problem below....

e10b 1500/ 9620 0.779s/batch, 125.0m/epoch
class_loss    0.895754
rel_loss      0.144881
total         1.040635
dtype: float64
-----------
./train_models_sgcls.sh: line 29: 32492 Segmentation fault      python /home/jungjunkim/neural-motifs-master/models/train_rels.py -m sgcls -model motifnet -order leftright -nl_obj 2 -nl_edge 4 -b 3 -clip 5 -p 100 -hidden_dim 512 -pooling_dim 4096 -lr 1e-3 -ngpu 2 -ckpt checkpoints/vgdet/vg-24.tar -save_dir checkpoints/motifnet2 -nepoch 50 -use_bias

at the 10 epoch... I got the error of segmentation fault first, but I don't know the cause...

**Comment by haoopan** [comment]
Have you solved this problem?
