### ISSUE TITLE
Why is the groundtruth different from true visual genome dataset

### ISSUE THREAD

**Issue by jungjun9150** [rowanz/neural-motifs#72]
![vgpic](https://user-images.githubusercontent.com/25945078/62278827-d17f3100-b483-11e9-898f-dee461109925.png)
![imgbox-3072](https://user-images.githubusercontent.com/25945078/62278847-da700280-b483-11e9-8ca5-9cabac8b24c3.jpg)

the below is your visualize.py's result 
It is different from visual genome explore and
there is only one prediction and Yours have less groundtruth

Please let me inform how to get the right result like your paper qualitative result or your demo's result

**Comment by Scarecrow0** [comment]
The dataset this work uses is a sub-set of Visual Genome dataset, which comes from this paper. [Check this out.](http://arxiv.org/abs/1701.02426)
