### ISSUE TITLE
about the __background__

### ISSUE THREAD

**Issue by tingxueronghua** [rowanz/neural-motifs#76]
I follow the notes in the read.me and can get results. But each time I run the code, I get something like this:
"
loading word vectors from ……neural-motifs/data/glove.6B.200d.pt
__background__ -> __background__ 
fail on __background__
loading word vectors from ……neural-motifs/data/glove.6B.100d.pt
__background__ -> __background__ 
fail on __background__
"
and I haven't got any idea where it comes from. Does it means something wrong?

**Comment by rowanz** [comment]
Hmm I'm not sure! possibly your GloVe path is incorrect? But if you're training from scratch then you might want to actually comment out the part where it loads in the GloVe embeddings, I'm not convinced they help :)

**Comment by tingxueronghua** [comment]
Thank you! But I use the pretrained model to inference the results...

**Comment by simonJJJ** [comment]
I think the reason is in code lib/word_vectors.py
line 23 -> line 37

**Comment by jungjun9150** [comment]
@simonJJJ 
what codes do we have to change?

**Comment by congvmit** [comment]
@tingxueronghua 
Have you fixed this issue?

**Comment by tingxueronghua** [comment]
> @tingxueronghua
> Have you fixed this issue?

I am sorry but I gave up and didn't try fixing it after that time.

**Comment by leonodelee** [comment]
> @tingxueronghua Have you fixed this issue?
Have you fixed this issue?

**Comment by leonodelee** [comment]
> I think the reason is in code lib/word_vectors.py line 23 -> line 37
Have you fixed this issue?

**Comment by tingxueronghua** [comment]
> > @tingxueronghua Have you fixed this issue?
> > Have you fixed this issue?

No, I have not. As I said above, I did not focus on this task any more.
