### ISSUE TITLE
please can you detail all the dependencies?

### ISSUE THREAD

**Issue by galsk87** [rowanz/neural-motifs#8]
I tried building and needed cython for example, i installed cython and still had this error 

sgalk87@rishon1:~/neural-motifs$ make
cd lib/draw_rectangles; python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
Makefile:6: recipe for target 'draw_rectangles' failed
make: *** [draw_rectangles] Error 1

thanks

**Comment by rowanz** [comment]
Hi Gal,

Sure, it'll have to wait a few days (I'm near a deadline rn). In the
meantime I think your problem is that cython is not installed. I highly
recommend you use anaconda, which I think has cython built in, but if not
then run

`conda install cython`

Or if you want to use pip,

`pip install --upgrade cython`

Let me know if that fixes things!!

**Comment by galsk87** [comment]
ok i solved it with conda.

thanks.
i also had problems with downloading your pre trained checkpoint for the detector and when i tried training i got the next error:


Traceback (most recent call last):
  File "models/train_detector.py", line 33, in <module>
    filter_empty_rels=False, use_proposals=conf.use_proposals)
  File "/home/sgalk87/neural-motifs/dataloaders/visual_genome.py", line 136, in splits
    train = cls('train', *args, **kwargs)
  File "/home/sgalk87/neural-motifs/dataloaders/visual_genome.py", line 60, in __init__
    self.filenames = load_image_filenames(image_file)
  File "/home/sgalk87/neural-motifs/dataloaders/visual_genome.py", line 260, in load_image_filenames
    assert len(fns) == 108073
AssertionError

do you have and idea how to solve it?

**Comment by rowanz** [comment]
1) for the Visual Genome issue, it looks like you have a different number of filenames - did you follow the steps I listed in the repo to download the dataset?

2) what checkpoint are you trying?

**Comment by galsk87** [comment]
I solved the first proble-your correct.

Im talking about the pre trained detector.

Thabks,
Gal.

בתאריך יום ב׳, 21 במאי 2018, 0:05, מאת Rowan Zellers ‏<
notifications@github.com>:

**Comment by rowanz** [comment]
Ah, so I think the confusion lies in that the checkpoint isn't really a tar file, it's whatever format pytorch uses to save things (presumably pickle). Let me know if running the code in the repo doesn't work!

**Comment by rowanz** [comment]
you're using the wrong version of pytorch, see #7

**Comment by galsk87** [comment]
i see do you happen to know the correct installation command, cause there are a lot of versions and i couldnt dig up the right one.

**Comment by galsk87** [comment]
solved, please leave issue open for other issues.

**Comment by galsk87** [comment]
when trying to train im getting the next error

    self.prev_idx = torch._C._cuda_getDevice()
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at torch/csrc/cuda/Module.cpp:107

while when i'm doing nvidia-smi 


Fri May 25 12:57:10 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:08:00.0 Off |                  N/A |
| 23%   27C    P0    58W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:0F:00.0 Off |                  N/A |
| 23%   26C    P0    55W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+


and when i'm doing torch.cuda.is_available() i get true.

Do you know how to handle this error?

**Comment by galsk87** [comment]
when you run the command
 ./scripts/train_models_sgcls.sh 2

the input number 2 is exported to cuda visable devices, meaning you are training on GPU #2 so in fact this created the error.

**Comment by rrryan2016** [comment]
Hey there, 

I came across the same Visual Genome issue, 

> ok i solved it with conda.
> 
> thanks.
> i also had problems with downloading your pre trained checkpoint for the detector and when i tried training i got the next error:
> 
> Traceback (most recent call last):
> File "models/train_detector.py", line 33, in
> filter_empty_rels=False, use_proposals=conf.use_proposals)
> File "/home/sgalk87/neural-motifs/dataloaders/visual_genome.py", line 136, in splits
> train = cls('train', *args, **kwargs)
> File "/home/sgalk87/neural-motifs/dataloaders/visual_genome.py", line 60, in **init**
> self.filenames = load_image_filenames(image_file)
> File "/home/sgalk87/neural-motifs/dataloaders/visual_genome.py", line 260, in load_image_filenames
> assert len(fns) == 108073
> AssertionError
> 
> do you have and idea how to solve it?

Mine is as below,


`Traceback (most recent call last):
  File "/media/nopanic/DATA/AnExperiment/NeuralMotifs/neural-motifs-master/models/train_detector.py", line 33, in <module>
    filter_empty_rels=False, use_proposals=conf.use_proposals)
  File "/media/nopanic/DATA/AnExperiment/NeuralMotifs/neural-motifs-master/dataloaders/visual_genome.py", line 136, in splits
    train = cls('train', *args, **kwargs)
  File "/media/nopanic/DATA/AnExperiment/NeuralMotifs/neural-motifs-master/dataloaders/visual_genome.py", line 60, in __init__
    self.filenames = load_image_filenames(image_file)
  File "/media/nopanic/DATA/AnExperiment/NeuralMotifs/neural-motifs-master/dataloaders/visual_genome.py", line 260, in load_image_filenames
    assert len(fns) == 108073
AssertionError`

I do carefully follow your steps in how to download the dataset. 
In the VG_100K folder, there are `108,249items, totalling 15.3 GB. `
Could you please give me some suggestions? 

best wishes,
Wenzhe Liu

**Comment by rrryan2016** [comment]
This problem is over! I did something wrong in the path `config.py` 
I am soooo STUPID LOL

> Hey there,
> 
> I came across the same Visual Genome issue,
> 
> > ok i solved it with conda.
> > thanks.
> > i also had problems with downloading your pre trained checkpoint for the detector and when i tried training i got the next error:
> > Traceback (most recent call last):
> > File "models/train_detector.py", line 33, in
> > filter_empty_rels=False, use_proposals=conf.use_proposals)
> > File "/home/sgalk87/neural-motifs/dataloaders/visual_genome.py", line 136, in splits
> > train = cls('train', *args, **kwargs)
> > File "/home/sgalk87/neural-motifs/dataloaders/visual_genome.py", line 60, in **init**
> > self.filenames = load_image_filenames(image_file)
> > File "/home/sgalk87/neural-motifs/dataloaders/visual_genome.py", line 260, in load_image_filenames
> > assert len(fns) == 108073
> > AssertionError
> > do you have and idea how to solve it?
> 
> Mine is as below,
> 
> `Traceback (most recent call last): File "/media/nopanic/DATA/AnExperiment/NeuralMotifs/neural-motifs-master/models/train_detector.py", line 33, in <module> filter_empty_rels=False, use_proposals=conf.use_proposals) File "/media/nopanic/DATA/AnExperiment/NeuralMotifs/neural-motifs-master/dataloaders/visual_genome.py", line 136, in splits train = cls('train', *args, **kwargs) File "/media/nopanic/DATA/AnExperiment/NeuralMotifs/neural-motifs-master/dataloaders/visual_genome.py", line 60, in __init__ self.filenames = load_image_filenames(image_file) File "/media/nopanic/DATA/AnExperiment/NeuralMotifs/neural-motifs-master/dataloaders/visual_genome.py", line 260, in load_image_filenames assert len(fns) == 108073 AssertionError`
> 
> I do carefully follow your steps in how to download the dataset.
> In the VG_100K folder, there are `108,249items, totalling 15.3 GB. `
> Could you please give me some suggestions?
> 
> best wishes,
> Wenzhe Liu

**Comment by tingxueronghua** [comment]
Well, just to take notice that the path in the README.md and the path in the config.py are not the same. I also find myself stupid.
