### ISSUE TITLE
value range of object feature vectors and relation feature vectors

### ISSUE THREAD

**Issue by bragilee** [rowanz/neural-motifs#81]
Hi,

Thank you so much for your work!!
I have one small question about the implementations. When I checked how you do the roi pooling for both objects and relations (object-pairs), I found the value range are different. Specifically, roi pooling for objects generate the object feature maps (N\*4096) which are in range of (0,positive infinite) because ReLU is used, but roi pooling for relations generate the relation feature maps (M*4096) which are in range of R (real numbers) because no ReLU is used. 
https://github.com/rowanz/neural-motifs/blob/d05a251b705cedaa51599bf2906cfa4653b7a761/lib/rel_model.py#L366-L374

Did I miss something? I am wondering does it matter when we do messge passing in the following steps based on these object feature vectorsand relation feature vectors?
Thank you so much!

**Comment by rowanz** [comment]
good catch, I didn't notice this :) I'm not sure if there's an important distinction between them but I'd be curious to see experimental results one way or another 😄

**Comment by bragilee** [comment]
Probably it will not affect neural-motifs as there are LSTM and other operations following the faster rcnn. As I am trying to do some improvements on your code, where this would have effect on my task. 

Thank you. :)
