### ISSUE TITLE
Question about training model on ground truth boxes

### ISSUE THREAD

**Issue by seekingup** [rowanz/neural-motifs#85]
I found both `train_models_sgcls.sh` and `train_motifnet.sh` are trained using `-m sgcls`, even if it's then used for sgdet evaluation. I also checked the paper. It seems all models are trained on ground truth boxes. But in some scene graph generation codes, they train object detector and relation model jointly. What's the difference? Has anyone try to train motifnet on object detector's output? If yes, what the result is like?

**Comment by sharifza** [comment]
There is [another script](https://github.com/rowanz/neural-motifs/blob/master/scripts/refine_for_detection.sh) which fine-tunes the model trained in sgcl, given the object detector's output. That would give the results for SGdet setting.
