### ISSUE TITLE
File cannot be decompressed

### ISSUE THREAD

**Issue by TP0609** [rowanz/neural-motifs#88]
hello！
    The downloaded files vg-faster-rcnn.tar, vgrel-motifnet-sgcls, vgrel-motifnet-sgdet, these three files can not be decompressed. What command is used to decompress these three files?

**Comment by Spichon** [comment]
Why this issue is closed ? I'm encountering the same problem

**Comment by Lazy-poe** [comment]
I have the same problem with you.  How do you solve it ?
