### ISSUE TITLE
File cannot be decompressed

### ISSUE THREAD

**Issue by TP0609** [rowanz/neural-motifs#89]
thanks,
but after your fix, in res_model.py, meet this error.
if result.is_none():
return ValueError("heck")

_Originally posted by @GreenTeaHua in https://github.com/rowanz/neural-motifs/pull/73#issuecomment-552757692_

**Comment by TP0609** [comment]
@GreenTeaHua    hello! 
 I downloaded the relevant installation package for the program code (neural-motifs) on  github website (https://github.com/rowanz/neural-motifs), vg-faster-rcnn.tar, vgrel-motifnet-sgcls , vgrel-motifnet-sgdet; but these three files can not be properly decompressed, and some error messages show that: this compressed file is damaged, Can the three files you downloaded be properly decompressed? Or in the Linux system, how do I properly decompress these three files using the decompression command?

**Comment by GreenTeaHua** [comment]
@TP0609 
hello , i donot  use those  3 files,after  your dataset  is  setup ,u can train  for those  models  by  using  the  scripts
