### ISSUE TITLE
 undefined symbol: __cudaRegisterFatBinaryEnd

### ISSUE THREAD

**Issue by F0Wen** [rowanz/neural-motifs#90]
hi,i have encountered problems when i ran :~/code/Mono-3D/3d-vehicle-tracking-master.2/faster-rcnn.pytorch$ ./run_test.sh :
Traceback (most recent call last):
  File "test_net.py", line 30, in <module>
    from model.utils.net_utils import save_net, load_net, vis_detections
  File "/home/ld/code/Mono-3D/3d-vehicle-tracking-master.2/faster-rcnn.pytorch/lib/model/utils/net_utils.py", line 7, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/home/ld/code/Mono-3D/3d-vehicle-tracking-master.2/faster-rcnn.pytorch/lib/model/roi_crop/functions/roi_crop.py", line 3, in <module>
    from .._ext import roi_crop
  File "/home/ld/code/Mono-3D/3d-vehicle-tracking-master.2/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ImportError: /home/ld/code/Mono-3D/3d-vehicle-tracking-master.2/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaRegisterFatBinaryEnd

pytorch=0.4.1,cuda=9.0 and gcc=5.4.0 
can anybody solve it?Thanks!

**Comment by bknyaz** [comment]
Do you have several cuda versions? Make sure that _roi_crop.so is compiled with the same version of cuda you are running (i.e. 9.0). I had a similar problem and had to change /usr/local/cuda/bin/nvcc hardcoded in some makefile to the correct cuda version.
There is the same issue here: https://github.com/rowanz/neural-motifs/issues/65

**Comment by F0Wen** [comment]
Thank you, i compiled successfully with cuda9.0😁
________________________________
发件人: Boris Knyazev <notifications@github.com>
发送时间: 2019年11月20日 1:51
收件人: rowanz/neural-motifs <neural-motifs@noreply.github.com>
抄送: F0Wen <wenfan1995@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [rowanz/neural-motifs] undefined symbol: __cudaRegisterFatBinaryEnd (#90)


Do you have several cuda versions? Make sure that _roi_crop.so is compiled with the same version of cuda you are running (i.e. 9.0). I had a similar problem and had to change /usr/local/cuda/bin/nvcc hardcoded in some makefile to the correct cuda version.
