### ISSUE TITLE
Confused about SGDet 

### ISSUE THREAD

**Issue by malsulaimi** [rowanz/neural-motifs#97]
Hello , 

Thank you for this great work. 

I have read the paper and tried to compare the results I reproduced by running your code. I'm confused a small thing. I read the below snippet from the Neural MOTIF paper  : 
_" scene graph detection (SGDET): predict boxes, box labels, and edge labels."_

to my understanding this means that running the model with the aforementioned mode will produce a complete graph with classes ( objects ) and their edge labels ( predicate). However when I run the inference using SGDet with pretrained check points, I get the following  output: 

'pred_boxes', 'pred_classes', 'pred_rel_inds', 'obj_scores', 'rel_scores'
which I presume are bounding boxes , objects , relationships types between the objects and the score confidence of objects and relations. respectively. Am I right in this assumption ? 

if so , I have successfully converted pred_class to object labels without issues. But I'm really struggling with  pred_rel_inds, how is this mapped to the relationship type/name. 

appreciate your help.

Thank you

**Comment by rowanz** [comment]
`pred_rel_inds` stores which object IDs a given relationship is between (column 1- head object, column 2 - tail object), and then for evaluation I stack on a 3rd column of the relationship type  - see https://github.com/rowanz/neural-motifs/blob/5f6522fc535a126a9798900e13f207b6ae1eb013/lib/evaluation/sg_eval.py#L147 for more info. thanks!
